[package]
name = "cargo-leptos"
license = "MIT"
repository = "https://github.com/akesson/cargo-leptos"
description = "Build tool for Leptos."
categories = ["development-tools", "wasm", "web-programming"]
keywords = ["leptos"]
version = "0.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
anyhow_ext = { git = "https://github.com/gensmusic/anyhow_ext.git", branch = "main" }
log = "0.4"
flexi_logger = "0.24.1"
lightningcss = { version = "1.0.0-alpha.36", features = ["browserslist"] }
tokio = { version = "1", default-features = false, features = ["full"] }
axum = { version = "0.5", features = ["ws"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.3", features = ["fs"] }
# not using notify 5.0 because it uses Crossbeam which has an issue with tokio
notify = "4.0"
lazy_static = "1.4"
regex = "1.7"
binary-install = "0.0.2"
which = "4.3"
cargo_metadata = { version = "0.15", features = ["builder"] }
serde_json = "1.0"
wasm-bindgen-cli-support = "0.2"
ansi_term = "0.12"
once_cell = "1.16"
seahash = "4.1"
